### ISSUE TITLE
Workshop description

### ISSUE THREAD

**Issue by LitoChris** [dmahlow/cloudnein20#3]
@Pisush  Daniel, please add the following info on the website. Thank you. 
---

**Title:** 
Introduction to Monitoring with Grafana

**Summary:**
As software becomes more and more complex, the need to understand how it performs in production becomes an important part of software development. If you want to better understand your applications, this class is for you.

**Details:**
In this workshop, we'll cover the basics of monitoring, what to monitor, how to visualize it, and how to alert when things go wrong. We'll also look at how to combine metrics with logs to troubleshoot production issues.

During the day, we'll talk about:

- Time series
- Time series databases
- Collecting metrics with Prometheus
- Effective monitoring (RED, USE, golden signals)
- Dashboard design
- Logs

You'll also learn how to use Grafana, an open source platform for monitoring and observability, to set up your monitoring solution:

- Adding and configuring data sources
- Creating beautiful and functional dashboards
- Exploring logs with Loki

**Who this workshop is for:**
This workshop is meant for Software Developers, Site Reliability Engineers, Operators.

**What you'll learn:**

After this workshop:
- You'll have an understanding of how to monitor your software
- You'll be able to use Grafana to create dashboards and alerts
- You'll be able to use metrics and logs together to debug running software

**Prerequisites**:
Basic experience with web services.

**Bio:** 
Marcus Olsson is a Developer Advocate at Grafana Labs, the company behind Grafana. Before that he was consulting teams on cloud native practices and infrastructure. He's also known to draw gophers and organize Go meetups.

**Social media:**
https://github.com/marcusolsson
https://twitter.com/marcusolsson
https://linkedin.com/in/marcusolsson1

![profile](https://user-images.githubusercontent.com/56724108/70425653-e3946000-1a71-11ea-9b0d-a87cc5f8c1fb.png)

**Comment by Pisush** [comment]
@LitoChris added some styling, to tell the sections apart.
Could you reuse that in the future?

And - Looks good!

**Comment by LitoChris** [comment]
> @LitoChris added some styling, to tell the sections apart.
> Could you reuse that in the future?
> 
> And - Looks good!

Of course. Thank you!
